name: itvlist

on:
  schedule:
    - cron: '0 1 * * *'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install selenium requests futures eventlet

      - name: Run a
        run: python ${{ github.workspace }}/a.py
     
      - name: Run itv1
        run: python ${{ github.workspace }}/itv1.py

     # - name: run itv2
       # run: python ${{ github.workspace }}/itv2.py

      - name: Run itv_add
        run: python ${{ github.workspace }}/itv_add.py        
      
      - name: Run itvjoin
        run: python ${{ github.workspace }}/itvjoin.py


      - name: Run b
        run: python ${{ github.workspace }}/b.py

      - name: Run c
        run: python ${{ github.workspace }}/c.py        
        
        
      - name: 提交更改
        run: |
          git config --local user.email "dwc1119@163.com"
          git config --local user.name "dwc1119"
          git add .
          git commit *.txt -m "Add generated file"
          git commit *.m3u -m "Add generated file"
          #git pull --rebase
          git push -f

